// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJb60n1SxXdcDwdTcsFcPzQt848LM5RaA',
    appId: '1:703168627440:web:b5ad580c268e827e317835',
    messagingSenderId: '703168627440',
    projectId: 'ecommerceapp-6e2f4',
    authDomain: 'ecommerceapp-6e2f4.firebaseapp.com',
    storageBucket: 'ecommerceapp-6e2f4.firebasestorage.app',
    measurementId: 'G-BGWQMQG3CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3qYg01uohaZMAflRriPqwWLuYF43Ha6E',
    appId: '1:703168627440:android:5b6ab04979cb1cae317835',
    messagingSenderId: '703168627440',
    projectId: 'ecommerceapp-6e2f4',
    storageBucket: 'ecommerceapp-6e2f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkBYkaaesJrxCvQThMYOJ_VeJBNY055cg',
    appId: '1:703168627440:ios:a29d12f719709f6a317835',
    messagingSenderId: '703168627440',
    projectId: 'ecommerceapp-6e2f4',
    storageBucket: 'ecommerceapp-6e2f4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkBYkaaesJrxCvQThMYOJ_VeJBNY055cg',
    appId: '1:703168627440:ios:a29d12f719709f6a317835',
    messagingSenderId: '703168627440',
    projectId: 'ecommerceapp-6e2f4',
    storageBucket: 'ecommerceapp-6e2f4.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJb60n1SxXdcDwdTcsFcPzQt848LM5RaA',
    appId: '1:703168627440:web:0e235d6537b27396317835',
    messagingSenderId: '703168627440',
    projectId: 'ecommerceapp-6e2f4',
    authDomain: 'ecommerceapp-6e2f4.firebaseapp.com',
    storageBucket: 'ecommerceapp-6e2f4.firebasestorage.app',
    measurementId: 'G-2WGX89F7FB',
  );
}
